---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template EC2: This template creates an EFS, its security group, and 
  a mount point residing in a subnet with a database instance. **NOTE** Config based on wordpress
  instances.
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  DataSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The list of SubnetIds that hold the RDS & Redis instances in your Virtual Private Cloud (VPC)
    ConstraintDescription: >-
      must be a list of at least two existing subnets associated with at least
      two different availability zones. They should be residing in the selected
      Virtual Private Cloud. 
  EFSThroughputMode:
    Default: provisioned
    Description: The throughput mode for the file system to be created.
    Type: String
    AllowedValues:
    - provisioned
    - bursting
    ConstraintDescription: must be either bursting or provisioned
  EFSPerformanceMode:
    Description: The performance mode of the file system. 
    Default: generalPurpose
    Type: String
    AllowedValues:
    - generalPurpose
    - maxIO
    ConstraintDescription: must be either general purpose or max IO 
  EFSProvisionedThroughput:
    Default: 300
    Description: The throughput, measured in MiB/s, that you want to provision for the file system. Required if 'ThroughputMode' is set to 'provisioned'.
    Type: Number
    MinValue: '1'
    MaxValue: '1024'
    ConstraintDescription: must be between 1 and 1024MiB/s.
Resources:
  EFS:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: false
      FileSystemTags: 
        - Key: Name
          Value: Wordpress instances EFS
      # KmsKeyId: String
      # LifecyclePolicies: 
      #   - LifecyclePolicy
      PerformanceMode: 
        Ref: EFSPerformanceMode
      ProvisionedThroughputInMibps: 
        Ref: EFSProvisionedThroughput
      ThroughputMode: 
        Ref: EFSThroughputMode
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open EFS for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '2049'
        ToPort: '2049'
        # SourceSecurityGroupId:
        #   Ref: WebServerSecurityGroup
      VpcId:
        Ref: VpcId
  EFSMountPoint:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId:
        Ref: EFS
      # IpAddress: String
      SecurityGroups: 
        - Ref: EFSSecurityGroup
      SubnetId: 
        Ref: DataSubnets